/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.searchlight.dev/icinga-operator/apis/monitoring/v1alpha1"
	scheme "go.searchlight.dev/icinga-operator/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeAlertsGetter has a method to return a NodeAlertInterface.
// A group's client should implement this interface.
type NodeAlertsGetter interface {
	NodeAlerts(namespace string) NodeAlertInterface
}

// NodeAlertInterface has methods to work with NodeAlert resources.
type NodeAlertInterface interface {
	Create(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.CreateOptions) (*v1alpha1.NodeAlert, error)
	Update(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.UpdateOptions) (*v1alpha1.NodeAlert, error)
	UpdateStatus(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.UpdateOptions) (*v1alpha1.NodeAlert, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeAlert, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeAlertList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeAlert, err error)
	NodeAlertExpansion
}

// nodeAlerts implements NodeAlertInterface
type nodeAlerts struct {
	client rest.Interface
	ns     string
}

// newNodeAlerts returns a NodeAlerts
func newNodeAlerts(c *MonitoringV1alpha1Client, namespace string) *nodeAlerts {
	return &nodeAlerts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeAlert, and returns the corresponding nodeAlert object, and an error if there is any.
func (c *nodeAlerts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeAlert, err error) {
	result = &v1alpha1.NodeAlert{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodealerts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeAlerts that match those selectors.
func (c *nodeAlerts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeAlertList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeAlertList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeAlerts.
func (c *nodeAlerts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeAlert and creates it.  Returns the server's representation of the nodeAlert, and an error, if there is any.
func (c *nodeAlerts) Create(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.CreateOptions) (result *v1alpha1.NodeAlert, err error) {
	result = &v1alpha1.NodeAlert{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeAlert).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeAlert and updates it. Returns the server's representation of the nodeAlert, and an error, if there is any.
func (c *nodeAlerts) Update(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.UpdateOptions) (result *v1alpha1.NodeAlert, err error) {
	result = &v1alpha1.NodeAlert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodealerts").
		Name(nodeAlert.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeAlert).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeAlerts) UpdateStatus(ctx context.Context, nodeAlert *v1alpha1.NodeAlert, opts v1.UpdateOptions) (result *v1alpha1.NodeAlert, err error) {
	result = &v1alpha1.NodeAlert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodealerts").
		Name(nodeAlert.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeAlert).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeAlert and deletes it. Returns an error if one occurs.
func (c *nodeAlerts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodealerts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeAlerts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodealerts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeAlert.
func (c *nodeAlerts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeAlert, err error) {
	result = &v1alpha1.NodeAlert{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodealerts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
