/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.searchlight.dev/icinga-operator/apis/monitoring/v1alpha1"
	scheme "go.searchlight.dev/icinga-operator/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SearchlightPluginsGetter has a method to return a SearchlightPluginInterface.
// A group's client should implement this interface.
type SearchlightPluginsGetter interface {
	SearchlightPlugins() SearchlightPluginInterface
}

// SearchlightPluginInterface has methods to work with SearchlightPlugin resources.
type SearchlightPluginInterface interface {
	Create(ctx context.Context, searchlightPlugin *v1alpha1.SearchlightPlugin, opts v1.CreateOptions) (*v1alpha1.SearchlightPlugin, error)
	Update(ctx context.Context, searchlightPlugin *v1alpha1.SearchlightPlugin, opts v1.UpdateOptions) (*v1alpha1.SearchlightPlugin, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SearchlightPlugin, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SearchlightPluginList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SearchlightPlugin, err error)
	SearchlightPluginExpansion
}

// searchlightPlugins implements SearchlightPluginInterface
type searchlightPlugins struct {
	client rest.Interface
}

// newSearchlightPlugins returns a SearchlightPlugins
func newSearchlightPlugins(c *MonitoringV1alpha1Client) *searchlightPlugins {
	return &searchlightPlugins{
		client: c.RESTClient(),
	}
}

// Get takes name of the searchlightPlugin, and returns the corresponding searchlightPlugin object, and an error if there is any.
func (c *searchlightPlugins) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SearchlightPlugin, err error) {
	result = &v1alpha1.SearchlightPlugin{}
	err = c.client.Get().
		Resource("searchlightplugins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SearchlightPlugins that match those selectors.
func (c *searchlightPlugins) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SearchlightPluginList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SearchlightPluginList{}
	err = c.client.Get().
		Resource("searchlightplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested searchlightPlugins.
func (c *searchlightPlugins) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("searchlightplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a searchlightPlugin and creates it.  Returns the server's representation of the searchlightPlugin, and an error, if there is any.
func (c *searchlightPlugins) Create(ctx context.Context, searchlightPlugin *v1alpha1.SearchlightPlugin, opts v1.CreateOptions) (result *v1alpha1.SearchlightPlugin, err error) {
	result = &v1alpha1.SearchlightPlugin{}
	err = c.client.Post().
		Resource("searchlightplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(searchlightPlugin).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a searchlightPlugin and updates it. Returns the server's representation of the searchlightPlugin, and an error, if there is any.
func (c *searchlightPlugins) Update(ctx context.Context, searchlightPlugin *v1alpha1.SearchlightPlugin, opts v1.UpdateOptions) (result *v1alpha1.SearchlightPlugin, err error) {
	result = &v1alpha1.SearchlightPlugin{}
	err = c.client.Put().
		Resource("searchlightplugins").
		Name(searchlightPlugin.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(searchlightPlugin).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the searchlightPlugin and deletes it. Returns an error if one occurs.
func (c *searchlightPlugins) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("searchlightplugins").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *searchlightPlugins) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("searchlightplugins").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched searchlightPlugin.
func (c *searchlightPlugins) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SearchlightPlugin, err error) {
	result = &v1alpha1.SearchlightPlugin{}
	err = c.client.Patch(pt).
		Resource("searchlightplugins").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
